development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: sample_sqlite3_development
  pool: 5
  username: root
  password: admin
  socket: /var/run/mysqld/mysqld.sock

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: sample_sqlite3_test
  pool: 5
  username: root
  password: admin
  socket: /var/run/mysqld/mysqld.sock

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: sample_sqlite3_production
  pool: 5
  username: root
  password: admin
  socket: /var/run/mysqld/mysqld.sock