development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: sample_sqlite3_development
  pool: 5
  username: root
  password: admin
  host: 10.200.71.94

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: sample_sqlite3_test
  pool: 5
  username: root
  password: admin
  host: 10.200.71.94

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: sample_sqlite3_production
  pool: 5
  username: root
  password: admin
  host: 10.200.71.94
